### ISSUE TITLE
Help me improve CakePHP's AuthComponent

### ISSUE THREAD

**Issue by ADmad** [loadsys/CakePHP-Stateless-Auth#13]
Your plugin's readme states:

> The provided component is intended to replace Cake's stock AuthCompnent (which has trouble not creating Sessions even when you explicitly tell it not to.)

AFAIK since 2.5 (or perhaps earlier) as long as the core AuthComponent is properly configured it does not trigger session starts. But if that isn't the case I would like to try and fix it. So can you please provide some info how are you configuring Auth and experiencing sessions being created by it when it shouldn't.

**Comment by beporter** [comment]
Thanks for the question.

The impetus for this originally occurred months ago. We're only open sourcing now because it's going to benefit a second project, so my recollection of the original troubleshooting is admittedly imperfect.

All I can really tell you is that during our initial app implementation, we kept ending up with `$_SESSION` being non-empty and Cake cookies being passed back and forth. One extremely annoying side-effect being blank `Auth->user()` data showing up (because the session was active) instead of engaging the authenticate object to fetch the proper record from the database with each request including the HTTP header containing a valid auth token.

This was even after setting and double- and triple-checking `sessionKey => false` in the `AppController::$components` config.

It may very well have been residual stuff left over from previous session-enabled connections, but it was persistent enough and causing enough of a problem that it made sense to absolutely guarantee that `SessionComponent` was _never_ involved. Our issues have disappeared since then, but I readily admit that might be incidental.

So honestly I don't think there's anything you need to do to improve the core AuthComponent-- it works fine in all of the typical use cases. Ours is just apparently not typical enough. If on the off chance there *is* a malfunction in the core AuthComponent when it comes to avoiding sessions, I'm afraid I'm no longer going to be much help in identifying it.

We'll of course update the readme though so as not to impinge your honor without proof. That's definitely inappropriate.

Thanks again for the interest.

**Comment by ADmad** [comment]
I'll be happy if the README it updated :smile: 

If at anytime in future you are able to reproduce the issue, a ticket would be most welcome. Thanks.
